definitions:
  dto.CodeSystem:
    properties:
      concept:
        items:
          $ref: '#/definitions/dto.Concept'
        type: array
      content:
        description: Complete
        type: string
      id:
        description: NAMASTE
        type: string
      name:
        description: NAMASTE Codes
        type: string
      resourceType:
        description: CodeSystem
        type: string
      status:
        description: active
        type: string
      url:
        type: string
      version:
        type: string
    type: object
  dto.Concept:
    properties:
      code:
        description: code
        type: string
      definition:
        description: longDesc
        type: string
      display:
        description: Term
        type: string
      property:
        items:
          $ref: '#/definitions/dto.Property'
        type: array
    type: object
  dto.Contain:
    properties:
      code:
        description: code
        type: string
      display:
        description: term
        type: string
      extension:
        $ref: '#/definitions/dto.Extension'
      system:
        description: link to namaste/icd code system page
        type: string
    type: object
  dto.Error:
    properties:
      error:
        type: string
    type: object
  dto.Expansion:
    properties:
      contains:
        items:
          $ref: '#/definitions/dto.Contain'
        type: array
      identifier:
        description: link to autocomplete endpoint
        type: string
      offset:
        description: "0"
        type: integer
      timestamp:
        type: string
      total:
        description: "2"
        type: integer
    type: object
  dto.Extension:
    properties:
      url:
        description: link to structure defintion
        type: string
      valueString:
        description: NAMASTE/ICD
        type: string
    type: object
  dto.Message:
    properties:
      message:
        type: string
    type: object
  dto.Property:
    properties:
      code:
        description: type
        type: string
      valueString:
        description: ayurveda/siddha/unani
        type: string
    type: object
  dto.ValueSet:
    properties:
      expansion:
        $ref: '#/definitions/dto.Expansion'
      id:
        description: autocomplete-results
        type: string
      resourceType:
        description: ValueSet
        type: string
      status:
        description: active
        type: string
    type: object
info:
  contact: {}
paths:
  /autocomplete:
    get:
      description: Retrieves matches by combining results from ICD and NAMASTE repositories
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ValueSet'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Retrive matches
  /codesystem/icd:
    get:
      parameters:
      - description: Number of codes you want
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CodeSystem'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: List all ICD codes
      tags:
      - Code System
  /codesystem/namaste:
    get:
      parameters:
      - description: Number of codes you want
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CodeSystem'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: List all namaste codes
      tags:
      - Code System
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
      summary: Check if server is alive
  /sync:
    get:
      description: Updates the database index with the NAMASTE CSV files' data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Syncs databases
swagger: "2.0"
